version: "3"

volumes:
  postgres_volume:

services:
  postgreSQL:
    image: "timescale/timescaledb:2.11.1-pg14"  # Use TimescaleDB with PostgreSQL 14
    container_name: "Link-shortening-db"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 1m
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: "Link-shortening-service"
    ports:
      - "8080:8080"
    depends_on:
      - postgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgreSQL/postgres

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin