version: "3"

volumes:
  postgres_volume:

services:
  postgreSQL:
    image: "postgres:15"
    container_name: "Link-shortening-db"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB='link-shortening'"
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 1m
      timeout: 10s
      retries: 5

  app:
    build: /
    container_name: "Link-shortening-service"
    ports:
      - "8080:8080"
    depends_on:
      - postgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgreSQL/link-shortening