# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    #    For local usage
#    url: jdbc:postgresql://localhost:5432/example
    #    For docker
    url: jdbc:postgresql://postgres/postgres
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
# Server configuration
server:
  port: 8080

front-end-url: http://localhost:3000
